### ISSUE TITLE
mod causing crash

### ISSUE THREAD

**Issue by TsplayerT** [MatrexsVigil/phc2trees#29]
It occurred several times without being consecutive, it usually opens the game without any problem, but this error has appeared more than 5 times

[latest.log](https://github.com/MatrexsVigil/phc2trees/files/5742463/latest.log)
![Screenshot_2](https://user-images.githubusercontent.com/6465230/103142747-9d935400-46e7-11eb-9e7d-4fc3131e6fc9.png)

**Comment by ghost** [comment]
I get the same screen but my log has different issues than his:

`[10Jan2021 13:24:47.917] [Worker-Main-13/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: 1024
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$3035/1986344112@ad3ba3d
java.lang.ArrayIndexOutOfBoundsException: 1024
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.rehash(Object2FloatOpenHashMap.java:1124)
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.insert(Object2FloatOpenHashMap.java:272)
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.put(Object2FloatOpenHashMap.java:280)
	at com.pam.pamhc2trees.init.CompostRegistry.register(CompostRegistry.java:56)
	at com.pam.pamhc2trees.SideProxy.commonSetup(SideProxy.java:58)
	at com.pam.pamhc2trees.SideProxy$$Lambda$9703/1531891493.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus$$Lambda$3035/1986344112.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121)
	at net.minecraftforge.fml.ModContainer$$Lambda$3573/1853720396.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[10Jan2021 13:24:47.921] [Worker-Main-10/INFO] [druidcraft/]: Setup method registered.
[10Jan2021 13:24:47.918] [Worker-Main-13/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLCommonSetupEvent dispatch for modid pamhc2trees
java.lang.ArrayIndexOutOfBoundsException: 1024
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.rehash(Object2FloatOpenHashMap.java:1124) ~[fastutil-8.2.1.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.insert(Object2FloatOpenHashMap.java:272) ~[fastutil-8.2.1.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.put(Object2FloatOpenHashMap.java:280) ~[fastutil-8.2.1.jar:?]
	at com.pam.pamhc2trees.init.CompostRegistry.register(CompostRegistry.java:56) ~[?:1.0.0]
	at com.pam.pamhc2trees.SideProxy.commonSetup(SideProxy.java:58) ~[?:1.0.0]
	at com.pam.pamhc2trees.SideProxy$$Lambda$9703/1531891493.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3035/1986344112.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) [?:35.1]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) [?:?]
	at net.minecraftforge.fml.ModContainer$$Lambda$3573/1853720396.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]`

**Comment by ghost** [comment]
`A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.rehash(Object2FloatOpenHashMap.java:1124) ~[fastutil-8.2.1.jar:?] {re:classloading}
-- MOD pamhc2trees --
Details:
	Mod File: pamhc2trees-1.16.3-1.0.0.jar
	Failure message: Pam's HarvestCraft 2 Fruit Trees (pamhc2trees) encountered an error during the common_setup event phase
		java.lang.ArrayIndexOutOfBoundsException: 1024
	Mod Version: 1.0.0
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ArrayIndexOutOfBoundsException: 1024
Stacktrace:
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.rehash(Object2FloatOpenHashMap.java:1124) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.insert(Object2FloatOpenHashMap.java:272) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap.put(Object2FloatOpenHashMap.java:280) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at com.pam.pamhc2trees.init.CompostRegistry.register(CompostRegistry.java:56) ~[?:1.0.0] {re:classloading}
	at com.pam.pamhc2trees.SideProxy.commonSetup(SideProxy.java:58) ~[?:1.0.0] {re:classloading}
	at com.pam.pamhc2trees.SideProxy$$Lambda$9703/1531891493.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3035/1986344112.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:35.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3573/1853720396.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}`

**Comment by ghost** [comment]
I have a feeling this is a forge issue and not specific to this mod, as druidcraft and potentially other mods have given a similar issue with fastutil index out of bounds exceptions, but, not sure.
